### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by wonderboy39** [wonderboy39/m2study#1]
# Requirements
- "miracle"이라는 이름의 directory 따로 생성해서 새로 할것
## Essential
- 회원가입 
  - [ ] join.jsp
  - [ ] join_ok.jsp

- 게시글 기능 (write.jsp, write_ok.jsp, view.jsp, view_all.jsp, modify.jsp)
  - [ ] write.jsp
  - [ ] write_ok.jsp
  - [ ] view_all.jsp
  - [ ] view.jsp
  - [ ] modify.jsp
  - [ ] delete.jsp

## Advanced
- 게시글 기능
  - [ ] 페이지 분리 (30개, 20개, ... 5개씩 볼수 있도록 하는 기능, using jquery ajax)

- 회원관리 기능 ( Admin )
  - [ ] members.jsp ( 모든 회원 조회, 회원 검색(by id, name) )

# PLAN
## Dec. 2016
 - 회원 가입, write.jsp, write_ok.jsp, view_all.jsp 
## Jan. 2017
 - view.jsp, modify.jsp, delete.jsp
 - ajax 도입, css, html개선, bootstrap사용여부 결정
